### ISSUE TITLE
TaskExecutor MVP

### ISSUE THREAD

**Issue by nygrenh** [rage/tmc-langs-rust#1]
Like
https://github.com/testmycode/tmc-langs/blob/master/tmc-langs-util/src/main/java/fi/helsinki/cs/tmc/langs/util/TaskExecutorImpl.java

https://github.com/testmycode/tmc-langs/blob/master/tmc-langs-util/src/main/java/fi/helsinki/cs/tmc/langs/util/TaskExecutor.java

**Comment by Heliozoa** [comment]
Done in d214e4e193ca0a46dfbb3f6e918cd8dbf19a4405
