### ISSUE TITLE
Panic raised when jvm.dll not found

### ISSUE THREAD

**Issue by ShootingStar91** [rage/tmc-langs-rust#163]
Crate `j4rs` panics [on this line](https://github.com/astonbitecode/j4rs/blob/master/rust/src/api_tweaks/generic.rs#L41) if JAVA_HOME environment variable is not set correctly or jvm.dll is not found from the path set as JAVA_HOME.

`thread 'main' panicked at 'Could find the jvm dynamic library: JavaLocatorError { description: "Java is not installed or not added in the system PATH" }', C:\Users\Arttu\.cargo\registry\src\github.com-1ecc6299db9ec823\j4rs-0.13.0\src\api_tweaks\generic.rs:41:38`

tmc-langs-rust calls it on [plugins/java/src/lib.rs line 115](https://github.com/rage/tmc-langs-rust/blob/master/plugins/java/src/lib.rs#L115)

**Comment by Heliozoa** [comment]
Thanks, this was previously taken care of by catching it in the langs CLI but I forgot to reconsider it when langs started being used as a library as well.
